[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "openinference-semantic-conventions"
dynamic = ["version"]
description = "OpenInference Semantic Conventions"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.7"
authors = [
  { name = "OpenInference Authors", email = "oss@arize.com" },
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]

[project.optional-dependencies]
test = []

[project.urls]
Homepage = "https://github.com/Arize-ai/openinference/tree/main/python/openinference-semantic-conventions"

[tool.hatch.version]
path = "src/openinference/semconv/version.py"

[tool.hatch.build.targets.sdist]
include = [
  "/src",
  "/tests",
]

[tool.hatch.build.targets.wheel]
packages = ["src/openinference"]
