version: 2
updates:
- directory: /java
  package-ecosystem: gradle
- directory: /js
  package-ecosystem: npm
- directory: /python
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-autogen-agentchat
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-anthropic
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-openai-agents
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-agno
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-crewai
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-autogen
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-litellm
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-instructor
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-bedrock
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-llama-index
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-google-genai
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-google-adk
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-openllmetry
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-guardrails
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-dspy
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-beeai
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-portkey
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-pydantic-ai
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-openai
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-mcp
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-smolagents
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-mistralai
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-groq
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-langchain
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-vertexai
  package-ecosystem: pip
- directory: python/instrumentation/openinference-instrumentation-haystack
  package-ecosystem: pip
- directory: js/packages/openinference-instrumentation-beeai
  package-ecosystem: npm
- directory: js/packages/openinference-instrumentation-openai
  package-ecosystem: npm
- directory: js/packages/openinference-instrumentation-mcp
  package-ecosystem: npm
- directory: js/packages/openinference-instrumentation-langchain
  package-ecosystem: npm 
