updates:
- directory: /java
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: gradle
  schedule:
    interval: weekly
- directory: /js
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: npm
  schedule:
    interval: weekly
- directory: /python
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-google-genai
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-openai-agents
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-mistralai
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-haystack
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-pydantic-ai
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-langchain
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-google-adk
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-llama-index
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-agno
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-beeai
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-dspy
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-autogen
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-smolagents
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-vertexai
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-openllmetry
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-groq
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-litellm
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-guardrails
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-portkey
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-bedrock
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-crewai
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-autogen-agentchat
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-anthropic
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-mcp
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-instructor
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: python/instrumentation/openinference-instrumentation-openai
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: pip
  schedule:
    interval: weekly
- directory: js/packages/openinference-instrumentation-langchain
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: npm
  schedule:
    interval: weekly
- directory: js/packages/openinference-instrumentation-beeai
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: npm
  schedule:
    interval: weekly
- directory: js/packages/openinference-mastra
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: npm
  schedule:
    interval: weekly
- directory: js/packages/openinference-instrumentation-bedrock-agent-runtime
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: npm
  schedule:
    interval: weekly
- directory: js/packages/openinference-semantic-conventions
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: npm
  schedule:
    interval: weekly
- directory: js/packages/openinference-instrumentation-bedrock
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: npm
  schedule:
    interval: weekly
- directory: js/packages/openinference-vercel
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: npm
  schedule:
    interval: weekly
- directory: js/packages/openinference-instrumentation-mcp
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: npm
  schedule:
    interval: weekly
- directory: js/packages/openinference-core
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: npm
  schedule:
    interval: weekly
- directory: js/packages/openinference-instrumentation-openai
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
    - version-update:semver-patch
  package-ecosystem: npm
  schedule:
    interval: weekly
version: 2

