services:
  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://phoenix:6006
