import type { Span, TracerProvider } from "@opentelemetry/api";
import { context, diag, SpanKind, SpanStatusCode, trace } from "@opentelemetry/api";
import { isTracingSuppressed } from "@opentelemetry/core";
import type { InstrumentationConfig } from "@opentelemetry/instrumentation";
import {
  InstrumentationBase,
  InstrumentationNodeModuleDefinition,
} from "@opentelemetry/instrumentation";
import { ATTR_HTTP_RESPONSE_STATUS_CODE } from "@opentelemetry/semantic-conventions";
import type * as TypeSafe from "@typesafe-ai/sdk";

import type { TraceConfig, TraceConfigOptions } from "@arizeai/openinference-core";
import { generateTraceConfig, OITracer, withSafety } from "@arizeai/openinference-core";
import {
  LLMProvider,
  LLMSystem,
  OpenInferenceSpanKind,
  SemanticConventions,
} from "@arizeai/openinference-semantic-conventions";

import { getRequestAttributes, getResponseAttributes } from "./attributes";
// oxlint-disable-next-line typescript/prefer-ts-expect-error
// @ts-ignore - Generated by prebuild.
import { VERSION } from "./version";

const { LLM_PROVIDER, LLM_SYSTEM, OPENINFERENCE_SPAN_KIND } = SemanticConventions;

const MODULE_NAME = "@typesafe-ai/sdk";
const INSTRUMENTATION_NAME = "@arizeai/openinference-instrumentation-typesafe";
/**
 * Semver ranges of `@typesafe-ai/sdk` that this instrumentor auto-patches via
 * the Node.js `require` hook.
 */
const SUPPORTED_VERSIONS = [">=0.6.0"];
type TypeSafeModule = typeof TypeSafe;

/**
 * Ownership map from a patched `TypeSafeClient` prototype to the instrumentor
 * that wrapped it. A {@link WeakMap} avoids mutating immutable ESM namespaces
 * and lets CommonJS and ESM builds of the SDK be patched independently.
 */
const owners = new WeakMap<TypeSafe.TypeSafeClient, TypeSafeInstrumentation>();

/**
 * Invokes a span-recording callback, logging and swallowing telemetry errors so
 * they never surface to the instrumented caller.
 */
const safelyRecord = withSafety({
  fn: (record: () => void) => {
    record();
  },
  onError: (error) => {
    diag.warn("TypeSafe instrumentation could not record telemetry", error);
  },
});

/**
 * OpenInference instrumentation for `@typesafe-ai/sdk`.
 *
 * Emits one OpenInference `LLM` span per `TypeSafeClient.systemOne` call,
 * including SDK retries. Does not instrument `models.list`. Request and
 * response bodies are recorded as JSON on `input.value` / `output.value`.
 *
 * Automatic patching covers CommonJS `require` loads. For ESM, bundlers, or
 * late imports, call {@link TypeSafeInstrumentation.manuallyInstrument}.
 *
 * @see {@link https://github.com/Arize-ai/openinference/blob/main/spec/semantic_conventions.md | OpenInference semantic conventions}
 */
export class TypeSafeInstrumentation extends InstrumentationBase<TypeSafeModule> {
  private oiTracer: OITracer;
  private readonly traceConfig: TraceConfig;
  private readonly manualModules = new Set<TypeSafeModule>();
  private readonly patchedModules = new Set<TypeSafeModule>();

  /**
   * @param options - Optional instrumentor configuration.
   * @param options.instrumentationConfig - OpenTelemetry instrumentation config.
   * @param options.traceConfig - OpenInference {@link TraceConfigOptions}.
   * @param options.tracerProvider - Tracer provider used to create spans.
   */
  constructor({
    instrumentationConfig,
    traceConfig,
    tracerProvider,
  }: {
    instrumentationConfig?: InstrumentationConfig;
    traceConfig?: TraceConfigOptions;
    tracerProvider?: TracerProvider;
  } = {}) {
    super(INSTRUMENTATION_NAME, VERSION, { ...instrumentationConfig });
    this.traceConfig = generateTraceConfig(traceConfig ?? {});
    this.oiTracer = new OITracer({ tracer: this.tracer, traceConfig: this.traceConfig });
    if (tracerProvider) this.setTracerProvider(tracerProvider);
  }

  /**
   * Registers the CommonJS module definition used for automatic `require`
   * patching of `@typesafe-ai/sdk`.
   *
   * @returns The Node.js module definition for this instrumentor.
   */
  protected init() {
    return new InstrumentationNodeModuleDefinition<TypeSafeModule>(
      MODULE_NAME,
      SUPPORTED_VERSIONS,
      (module) => this.patch(module),
      (module) => this.unpatch(module),
    );
  }

  /**
   * Rebinds the instrumentor to a new tracer provider.
   *
   * @param provider - Tracer provider used for subsequent spans.
   */
  setTracerProvider(provider: TracerProvider): void {
    super.setTracerProvider(provider);
    this.oiTracer = new OITracer({ tracer: this.tracer, traceConfig: this.traceConfig });
  }

  /**
   * Patches an already-imported `@typesafe-ai/sdk` namespace.
   *
   * Use this for ESM loads, bundlers, or modules imported before the
   * instrumentor was enabled. Safe to call for both CommonJS and ESM builds
   * in the same process.
   *
   * @param module - The imported `@typesafe-ai/sdk` module namespace.
   */
  manuallyInstrument(module: TypeSafeModule): void {
    this.manualModules.add(module);
    if (this.isEnabled()) this.patch(module);
  }

  enable(): void {
    super.enable();
    // InstrumentationBase calls enable from its constructor, before fields exist.
    if (!this.manualModules) return;
    for (const module of this.manualModules) this.patch(module);
  }

  disable(): void {
    super.disable();
    for (const module of this.patchedModules) this.unpatch(module);
  }

  private patch(module: TypeSafeModule): TypeSafeModule {
    const prototype = module.TypeSafeClient?.prototype;
    if (!prototype?.systemOne || owners.has(prototype)) return module;
    // The wrapper's `this` is the SDK client, so retain the instrumentor separately.
    // oxlint-disable-next-line typescript/no-this-alias
    const instrumentation = this;
    this._wrap(prototype, "systemOne", (original) => {
      return function systemOne<const Q extends TypeSafe.Questions>(
        this: TypeSafe.TypeSafeClient,
        request: TypeSafe.SystemOneRequest<Q>,
        options?: TypeSafe.RequestOptions,
      ): TypeSafe.APIPromise<TypeSafe.SystemOneResult<Q>> {
        const parent = context.active();
        if (isTracingSuppressed(parent)) return original.bind(this)(request, options);
        const span = instrumentation.oiTracer.startSpan(
          "TypeSafeClient.systemOne",
          {
            kind: SpanKind.CLIENT,
            attributes: {
              [OPENINFERENCE_SPAN_KIND]: OpenInferenceSpanKind.LLM,
              [LLM_PROVIDER]: LLMProvider.TYPESAFE,
              [LLM_SYSTEM]: LLMSystem.TYPESAFE,
            },
          },
          parent,
        );
        safelyRecord(() =>
          span.setAttributes(
            getRequestAttributes({
              request,
              options,
              defaultModel: this.defaultModel,
            }),
          ),
        );

        const recordError = (error: unknown) => {
          if (error instanceof module.APIError) {
            safelyRecord(() =>
              span.setAttributes({
                [ATTR_HTTP_RESPONSE_STATUS_CODE]: error.status,
              }),
            );
          }
          safelyRecord(() => {
            span.recordException(error instanceof Error ? error : String(error));
            span.setStatus({
              code: SpanStatusCode.ERROR,
              message: error instanceof Error ? error.message : String(error),
            });
            span.end();
          });
        };

        return context.with(trace.setSpan(parent, span), () => {
          try {
            const promise = original.bind(this)(request, options);
            return instrumentAPIPromise({ module, promise, span, recordError });
          } catch (error) {
            recordError(error);
            throw error;
          }
        });
      };
    });
    owners.set(prototype, this);
    this.patchedModules.add(module);
    return module;
  }

  private unpatch(module: TypeSafeModule): void {
    const prototype = module.TypeSafeClient.prototype;
    if (owners.get(prototype) !== this) return;
    this._unwrap(prototype, "systemOne");
    owners.delete(prototype);
    this.patchedModules.delete(module);
  }
}

/**
 * Wraps a TypeSafe `APIPromise` so response attributes are recorded once when
 * the promise settles, without changing caller-visible behavior.
 *
 * Prefer the SDK-parsed body when the caller awaits, maps, or uses
 * `withResponse()`. If the caller only uses `asResponse()` (or never consumes
 * the body), clone the response so telemetry can read JSON while leaving the
 * caller's body unread.
 *
 * @param args - Values needed to instrument the promise lifecycle.
 * @param args.module - The patched TypeSafe SDK module namespace.
 * @param args.promise - The original `APIPromise` returned by `systemOne`.
 * @param args.span - The active OpenInference span for this call.
 * @param args.recordError - Records the failure on `span` and ends it.
 * @returns An `APIPromise` with the same public API as `args.promise`.
 */
function instrumentAPIPromise<T>({
  module,
  promise,
  span,
  recordError,
}: {
  module: TypeSafeModule;
  promise: TypeSafe.APIPromise<T>;
  span: Span;
  recordError: (error: unknown) => void;
}): TypeSafe.APIPromise<T> {
  const rawResponse = promise.asResponse();
  let recorded = false;
  let ended = false;
  let preferSdkParse = false;

  const endOk = () => {
    if (ended) return;
    ended = true;
    safelyRecord(() => {
      span.setStatus({ code: SpanStatusCode.OK });
      span.end();
    });
  };

  const endError = (error: unknown) => {
    if (ended) return;
    ended = true;
    recordError(error);
  };

  const recordOnce = (result: unknown) => {
    if (recorded) return;
    recorded = true;
    safelyRecord(() => span.setAttributes(getResponseAttributes(result)));
  };

  const responsePromise = rawResponse.then(
    (response) => {
      // Clone immediately so asResponse callers can't consume the body first.
      const cloned = response.clone();
      void (async () => {
        await Promise.resolve();
        if (preferSdkParse) return;
        if (recorded) {
          endOk();
          return;
        }
        try {
          recordOnce(await cloned.json());
        } catch (error) {
          diag.debug("TypeSafe response telemetry could not be extracted", error);
          recordOnce(undefined);
        } finally {
          endOk();
        }
      })();
      return response;
    },
    (error: unknown) => {
      endError(error);
      throw error;
    },
  );

  return new module.APIPromise(responsePromise, async () => {
    preferSdkParse = true;
    try {
      const result = await promise;
      recordOnce(result);
      endOk();
      return result;
    } catch (error) {
      // The HTTP response may have succeeded while SDK parsing failed, in which
      // case the fallback path above has already bailed out on `preferSdkParse`.
      endError(error);
      throw error;
    }
  });
}
