import type { Span, TracerProvider } from "@opentelemetry/api";
import { context, diag, SpanKind, SpanStatusCode, trace } from "@opentelemetry/api";
import { isTracingSuppressed } from "@opentelemetry/core";
import type { InstrumentationConfig } from "@opentelemetry/instrumentation";
import {
  InstrumentationBase,
  InstrumentationNodeModuleDefinition,
} from "@opentelemetry/instrumentation";
import { ATTR_HTTP_RESPONSE_STATUS_CODE } from "@opentelemetry/semantic-conventions";
import type * as TypeSafe from "@typesafe-ai/sdk";

import type { TraceConfig, TraceConfigOptions } from "@arizeai/openinference-core";
import {
  generateTraceConfig,
  getMetadata,
  OITracer,
  withSafety,
} from "@arizeai/openinference-core";
import {
  LLMProvider,
  LLMSystem,
  OpenInferenceSpanKind,
  SemanticConventions,
} from "@arizeai/openinference-semantic-conventions";

import type { TypeSafeMetadataArgs } from "./attributes";
import {
  getRequestAttributes,
  getResponseAttributes,
  getTypeSafeMetadataAttributes,
} from "./attributes";
// oxlint-disable-next-line typescript/prefer-ts-expect-error
// @ts-ignore - Generated by prebuild.
import { VERSION } from "./version";

const { LLM_PROVIDER, LLM_SYSTEM, OPENINFERENCE_SPAN_KIND } = SemanticConventions;

const MODULE_NAME = "@typesafe-ai/sdk";
const INSTRUMENTATION_NAME = "@arizeai/openinference-instrumentation-typesafe";
/** Supported `@typesafe-ai/sdk` versions for automatic CommonJS patching. */
const SUPPORTED_VERSIONS = [">=0.6.0 <0.7.0"];
type TypeSafeModule = typeof TypeSafe;

/**
 * Maps each patched `TypeSafeClient` prototype to the instrumentor that owns it.
 * WeakMap avoids writing to immutable ESM namespaces and allows CJS/ESM builds
 * to be patched independently.
 */
const owners = new WeakMap<TypeSafe.TypeSafeClient, TypeSafeInstrumentation>();

/** Runs span recording without letting telemetry failures break the caller. */
const safelyRecord = withSafety({
  fn: (record: () => void) => {
    record();
  },
  onError: (error) => {
    diag.warn("TypeSafe instrumentation could not record telemetry", error);
  },
});

/**
 * OpenInference instrumentation for `@typesafe-ai/sdk`.
 *
 * One `LLM` span per `TypeSafeClient.systemOne` (including SDK retries).
 * `models.list` is not instrumented. Payloads are structured JSON — no chat
 * message attributes. Use {@link manuallyInstrument} for ESM / bundlers.
 *
 * The wrapper preserves `APIPromise` (`await`, `withResponse()`, `asResponse()`,
 * `map()`). When the caller only uses `asResponse()`, telemetry reads a response
 * clone so the caller's body stays unread; when the caller awaits/parses, attributes
 * come from the SDK parse and the clone is skipped.
 *
 * @see {@link https://github.com/Arize-ai/openinference/blob/main/spec/semantic_conventions.md | OpenInference semantic conventions}
 */
export class TypeSafeInstrumentation extends InstrumentationBase<TypeSafeModule> {
  private oiTracer: OITracer;
  private readonly traceConfig: TraceConfig;
  private readonly manualModules = new Set<TypeSafeModule>();
  private readonly patchedModules = new Set<TypeSafeModule>();

  constructor({
    instrumentationConfig,
    traceConfig,
    tracerProvider,
  }: {
    instrumentationConfig?: InstrumentationConfig;
    /**
     * OpenInference masking options. `hideInputMessages` / `hideOutputMessages`
     * have no effect — this instrumentor does not emit chat-message attributes.
     */
    traceConfig?: TraceConfigOptions;
    tracerProvider?: TracerProvider;
  } = {}) {
    super(INSTRUMENTATION_NAME, VERSION, { ...instrumentationConfig });
    this.traceConfig = generateTraceConfig(traceConfig ?? {});
    this.oiTracer = new OITracer({ tracer: this.tracer, traceConfig: this.traceConfig });
    if (tracerProvider) this.setTracerProvider(tracerProvider);
  }

  /** CommonJS module hook for `@typesafe-ai/sdk` (require-loaded only). */
  protected init() {
    return new InstrumentationNodeModuleDefinition<TypeSafeModule>(
      MODULE_NAME,
      SUPPORTED_VERSIONS,
      (module) => this.patch(module),
      (module) => this.unpatch(module),
    );
  }

  setTracerProvider(provider: TracerProvider): void {
    super.setTracerProvider(provider);
    this.oiTracer = new OITracer({ tracer: this.tracer, traceConfig: this.traceConfig });
  }

  /**
   * Patch an already-imported SDK namespace (ESM, bundlers, or late imports).
   * Safe for CJS and ESM builds in the same process.
   */
  manuallyInstrument(module: TypeSafeModule): void {
    this.manualModules.add(module);
    if (this.isEnabled()) this.patch(module);
  }

  enable(): void {
    super.enable();
    // InstrumentationBase calls enable from its constructor, before fields exist.
    if (!this.manualModules) return;
    for (const module of this.manualModules) this.patch(module);
  }

  disable(): void {
    super.disable();
    for (const module of this.patchedModules) this.unpatch(module);
  }

  private patch(module: TypeSafeModule): TypeSafeModule {
    const prototype = module.TypeSafeClient?.prototype;
    if (!prototype?.systemOne || owners.has(prototype)) return module;
    // The wrapper's `this` is the SDK client, so retain the instrumentor separately.
    // oxlint-disable-next-line typescript/no-this-alias
    const instrumentation = this;
    this._wrap(prototype, "systemOne", (original) => {
      return function systemOne<const Q extends TypeSafe.Questions>(
        this: TypeSafe.TypeSafeClient,
        request: TypeSafe.SystemOneRequest<Q>,
        options?: TypeSafe.RequestOptions,
      ): TypeSafe.APIPromise<TypeSafe.SystemOneResult<Q>> {
        const parent = context.active();
        if (isTracingSuppressed(parent)) return original.bind(this)(request, options);
        const span = instrumentation.oiTracer.startSpan(
          "TypeSafeClient.systemOne",
          {
            kind: SpanKind.CLIENT,
            attributes: {
              [OPENINFERENCE_SPAN_KIND]: OpenInferenceSpanKind.LLM,
              [LLM_PROVIDER]: LLMProvider.TYPESAFE,
              [LLM_SYSTEM]: LLMSystem.TYPESAFE,
            },
          },
          parent,
        );
        const config = instrumentation.traceConfig;
        const metadataArgs: TypeSafeMetadataArgs = {
          request,
          metadata: getMetadata(parent),
          config,
        };
        safelyRecord(() =>
          span.setAttributes(
            getRequestAttributes({
              request,
              options,
              defaultModel: this.defaultModel,
              config,
            }),
          ),
        );

        const recordError = (error: unknown) => {
          if (error instanceof module.APIError) {
            safelyRecord(() =>
              span.setAttributes({
                [ATTR_HTTP_RESPONSE_STATUS_CODE]: error.status,
                ...getTypeSafeMetadataAttributes({
                  ...metadataArgs,
                  requestId: error.requestId,
                }),
              }),
            );
          }
          safelyRecord(() => {
            span.recordException(error instanceof Error ? error : String(error));
            span.setStatus({
              code: SpanStatusCode.ERROR,
              message: error instanceof Error ? error.message : String(error),
            });
            span.end();
          });
        };

        return context.with(trace.setSpan(parent, span), () => {
          try {
            const promise = original.bind(this)(request, options);
            return instrumentAPIPromise({
              module,
              promise,
              span,
              metadataArgs,
              recordError,
            });
          } catch (error) {
            recordError(error);
            throw error;
          }
        });
      };
    });
    owners.set(prototype, this);
    this.patchedModules.add(module);
    return module;
  }

  private unpatch(module: TypeSafeModule): void {
    const prototype = module.TypeSafeClient.prototype;
    if (owners.get(prototype) !== this) return;
    this._unwrap(prototype, "systemOne");
    owners.delete(prototype);
    this.patchedModules.delete(module);
  }
}

function requestIdFrom(response: Response): string | undefined {
  return response.headers.get("x-typesafe-request-id") ?? undefined;
}

/**
 * Preserve APIPromise behavior while recording response attributes once.
 *
 * - Await / withResponse / map: prefer the SDK parse (no extra clone).
 * - asResponse-only / never consumed: clone + json so the caller's body stays unread
 *   and the span still ends.
 */
function instrumentAPIPromise<T>({
  module,
  promise,
  span,
  metadataArgs,
  recordError,
}: {
  module: TypeSafeModule;
  promise: TypeSafe.APIPromise<T>;
  span: Span;
  metadataArgs: TypeSafeMetadataArgs;
  recordError: (error: unknown) => void;
}): TypeSafe.APIPromise<T> {
  const rawResponse = promise.asResponse();
  let recorded = false;
  let ended = false;
  let preferSdkParse = false;

  const endOk = () => {
    if (ended) return;
    ended = true;
    safelyRecord(() => {
      span.setStatus({ code: SpanStatusCode.OK });
      span.end();
    });
  };

  const recordOnce = (result: unknown, requestId?: string) => {
    if (recorded) return;
    recorded = true;
    safelyRecord(() =>
      span.setAttributes({
        ...getResponseAttributes(result, metadataArgs.config),
        ...getTypeSafeMetadataAttributes({ ...metadataArgs, result, requestId }),
      }),
    );
  };

  const responsePromise = rawResponse.then(
    (response) => {
      // Clone immediately so asResponse callers can't consume the body first.
      const cloned = response.clone();
      void (async () => {
        await Promise.resolve();
        if (preferSdkParse) return;
        if (recorded) {
          endOk();
          return;
        }
        const requestId = requestIdFrom(response);
        try {
          recordOnce(await cloned.json(), requestId);
        } catch (error) {
          diag.debug("TypeSafe response telemetry could not be extracted", error);
          recordOnce(undefined, requestId);
        } finally {
          endOk();
        }
      })();
      return response;
    },
    (error: unknown) => {
      recordError(error);
      throw error;
    },
  );

  return new module.APIPromise(responsePromise, async () => {
    preferSdkParse = true;
    const [result, response] = await Promise.all([promise, rawResponse]);
    recordOnce(result, requestIdFrom(response));
    endOk();
    return result;
  });
}
