services:
  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - COLLECTOR_ENDPOINT=http://phoenix:6006/v1/traces
      # Set INSTRUMENT_DSPY=false to disable instrumentation
      - INSTRUMENT_DSPY=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CO_API_KEY=${CO_API_KEY}
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_BACKEND_URL=http://backend:8000
