import type * as AgentsModule from "@openai/agents";
import type { Tracer, TracerProvider } from "@opentelemetry/api";
import { diag } from "@opentelemetry/api";
import type {
  InstrumentationConfig,
  InstrumentationModuleDefinition,
} from "@opentelemetry/instrumentation";
import {
  InstrumentationBase,
  InstrumentationNodeModuleDefinition,
} from "@opentelemetry/instrumentation";

import type { TraceConfigOptions } from "@arizeai/openinference-core";
import { OITracer } from "@arizeai/openinference-core";

import { OpenInferenceTracingProcessor } from "./processor";
// oxlint-disable-next-line typescript/prefer-ts-expect-error
// @ts-ignore - generated by prebuild step
import { VERSION } from "./version";

export { VERSION };

const MODULE_NAME = "@openai/agents";
const INSTRUMENTATION_NAME = "@arizeai/openinference-instrumentation-openai-agents";

/**
 * Flag to track whether the agents module has been patched.
 * Used as a fallback when the module object is immutable.
 */
let _isOpenInferencePatched = false;

/**
 * Check if the agents module is currently instrumented.
 */
export function isPatched(): boolean {
  return _isOpenInferencePatched;
}

/**
 * OpenTelemetry-based instrumentation for the
 * [`@openai/agents`](https://www.npmjs.com/package/@openai/agents) SDK.
 *
 * Registers an {@link OpenInferenceTracingProcessor} with the SDK's native
 * tracing system to emit OpenInference-compliant spans without monkey-patching
 * any SDK methods.
 *
 * @example Auto-instrumentation (CommonJS)
 * ```typescript
 * import { NodeSDK } from "@opentelemetry/sdk-node";
 * import { OpenAIAgentsInstrumentation } from "@arizeai/openinference-instrumentation-openai-agents";
 *
 * const sdk = new NodeSDK({
 *   instrumentations: [new OpenAIAgentsInstrumentation()],
 * });
 * sdk.start();
 * ```
 *
 * @example Manual instrumentation (ESM)
 * ```typescript
 * import * as agents from "@openai/agents";
 * import { OpenAIAgentsInstrumentation } from "@arizeai/openinference-instrumentation-openai-agents";
 *
 * const instrumentation = new OpenAIAgentsInstrumentation({ tracerProvider: provider });
 * instrumentation.manuallyInstrument(agents);
 * ```
 */
export class OpenAIAgentsInstrumentation extends InstrumentationBase<typeof AgentsModule> {
  private oiTracer: OITracer;
  private tracerProvider?: TracerProvider;
  private traceConfig?: TraceConfigOptions;
  private processor?: OpenInferenceTracingProcessor;

  constructor({
    instrumentationConfig,
    traceConfig,
    tracerProvider,
  }: {
    /**
     * Standard OTel instrumentation configuration.
     * @see {@link InstrumentationConfig}
     */
    instrumentationConfig?: InstrumentationConfig;
    /**
     * OpenInference trace configuration for masking/redacting sensitive data.
     * @see {@link TraceConfigOptions}
     */
    traceConfig?: TraceConfigOptions;
    /**
     * Optional custom tracer provider. If not provided, the global provider is used.
     * @see {@link TracerProvider}
     */
    tracerProvider?: TracerProvider;
  } = {}) {
    super(INSTRUMENTATION_NAME, VERSION, Object.assign({}, instrumentationConfig));
    this.tracerProvider = tracerProvider;
    this.traceConfig = traceConfig;
    this.oiTracer = new OITracer({
      tracer: this.tracerProvider?.getTracer(INSTRUMENTATION_NAME, VERSION) ?? this.tracer,
      traceConfig,
    });
  }

  protected init(): InstrumentationModuleDefinition<typeof AgentsModule> {
    const module = new InstrumentationNodeModuleDefinition<typeof AgentsModule>(
      MODULE_NAME,
      [">=0.0.3"],
      this.patch.bind(this),
      this.unpatch.bind(this),
    );
    return module;
  }

  /**
   * Manually instruments the agents module. Required when the module is not
   * loaded via `require()` (e.g. ESM environments, bundlers, serverless).
   *
   * @param module - The `@openai/agents` module namespace object.
   */
  manuallyInstrument(module: typeof AgentsModule): void {
    diag.debug(`Manually instrumenting ${MODULE_NAME}`);
    this.patch(module);
  }

  get tracer(): Tracer {
    if (this.tracerProvider) {
      return this.tracerProvider.getTracer(this.instrumentationName, this.instrumentationVersion);
    }
    return super.tracer;
  }

  setTracerProvider(tracerProvider: TracerProvider): void {
    super.setTracerProvider(tracerProvider);
    this.tracerProvider = tracerProvider;
    this.oiTracer = new OITracer({
      tracer: this.tracer,
      traceConfig: this.traceConfig,
    });
    // Re-create processor with updated tracer if already patched
    if (this.processor) {
      this.processor = undefined;
    }
  }

  private patch(
    module: typeof AgentsModule & { openInferencePatched?: boolean },
    _moduleVersion?: string,
  ): typeof AgentsModule {
    diag.debug(`Applying patch for ${MODULE_NAME}@${_moduleVersion ?? "unknown"}`);

    if (module?.openInferencePatched || _isOpenInferencePatched) {
      return module;
    }

    const processor = this.getOrCreateProcessor();
    module.setTraceProcessors([processor]);

    _isOpenInferencePatched = true;
    try {
      module.openInferencePatched = true;
    } catch (_e) {
      // Module may be frozen in some environments
    }

    return module;
  }

  private unpatch(
    module: typeof AgentsModule & { openInferencePatched?: boolean },
    _moduleVersion?: string,
  ): void {
    diag.debug(`Removing patch for ${MODULE_NAME}@${_moduleVersion ?? "unknown"}`);
    module.setTraceProcessors([]);

    _isOpenInferencePatched = false;
    try {
      module.openInferencePatched = false;
    } catch (_e) {
      // Module may be frozen in some environments
    }
  }

  private getOrCreateProcessor(): OpenInferenceTracingProcessor {
    if (!this.processor) {
      this.processor = new OpenInferenceTracingProcessor({
        tracerProvider: this.tracerProvider,
        traceConfig: this.traceConfig,
      });
    }
    return this.processor;
  }
}
