import type {
  AgentSpanData,
  CustomSpanData,
  FunctionSpanData,
  GenerationSpanData,
  GenerationUsageData,
  HandoffSpanData,
  MCPListToolsSpanData,
  ResponseSpanData,
  Span,
  SpanData,
  Trace,
  TracingProcessor,
} from "@openai/agents";
import type { Attributes, HrTime, Span as OtelSpan, TracerProvider } from "@opentelemetry/api";
import { context, SpanStatusCode, trace } from "@opentelemetry/api";

import type { TraceConfigOptions } from "@arizeai/openinference-core";
import { OITracer, safelyJSONStringify } from "@arizeai/openinference-core";
import {
  GRAPH_NODE_ID,
  GRAPH_NODE_PARENT_ID,
  INPUT_MIME_TYPE,
  INPUT_VALUE,
  LLM_INPUT_MESSAGES,
  LLM_INVOCATION_PARAMETERS,
  LLM_MODEL_NAME,
  LLM_OUTPUT_MESSAGES,
  LLM_SYSTEM,
  LLM_TOKEN_COUNT_COMPLETION,
  LLM_TOKEN_COUNT_COMPLETION_DETAILS_REASONING,
  LLM_TOKEN_COUNT_PROMPT,
  LLM_TOKEN_COUNT_PROMPT_DETAILS_CACHE_READ,
  LLM_TOKEN_COUNT_TOTAL,
  LLM_TOOLS,
  LLMSystem,
  MESSAGE_CONTENT,
  MESSAGE_CONTENT_TEXT,
  MESSAGE_CONTENT_TYPE,
  MESSAGE_CONTENTS,
  MESSAGE_ROLE,
  MESSAGE_TOOL_CALL_ID,
  MESSAGE_TOOL_CALLS,
  MimeType,
  OpenInferenceSpanKind,
  OUTPUT_MIME_TYPE,
  OUTPUT_VALUE,
  SemanticConventions,
  TOOL_CALL_FUNCTION_ARGUMENTS_JSON,
  TOOL_CALL_FUNCTION_NAME,
  TOOL_CALL_ID,
  TOOL_JSON_SCHEMA,
  TOOL_NAME,
} from "@arizeai/openinference-semantic-conventions";

// oxlint-disable-next-line typescript/prefer-ts-expect-error
// @ts-ignore - generated by prebuild step
import { VERSION } from "./version";

const INSTRUMENTATION_NAME = "@arizeai/openinference-instrumentation-openai-agents";
const OPENINFERENCE_SPAN_KIND = SemanticConventions.OPENINFERENCE_SPAN_KIND;

/**
 * Maximum number of in-flight handoff entries kept in memory.
 *
 * A handoff entry is added when a handoff span ends, and removed when the
 * matching agent span starts. Mismatches (e.g. handoff spans that never
 * complete with a follow-up agent span) would otherwise leak memory.
 */
const MAX_HANDOFFS_IN_FLIGHT = 1000;

// ─── Type guards ─────────────────────────────────────────────────────────────

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isString(value: unknown): value is string {
  return typeof value === "string";
}

function isNumber(value: unknown): value is number {
  return typeof value === "number";
}

// ─── Time helpers ────────────────────────────────────────────────────────────

/**
 * Converts an ISO 8601 timestamp string to an OpenTelemetry {@link HrTime}
 * tuple `[seconds, remainder-in-nanoseconds]`.
 *
 * The OpenTelemetry SDK interprets a plain `number` `startTime` as either an
 * epoch-millisecond value or a `performance.now()` reading, so passing
 * nanoseconds as a single number truncates precision and confuses the
 * timeOrigin heuristic. Returning an `HrTime` tuple is unambiguous and
 * preserves sub-millisecond precision when the ISO string carries it.
 *
 * @example
 * isoToHrTime("2024-01-01T00:00:00.123456Z") → [1704067200, 123456000]
 */
function isoToHrTime(iso: string): HrTime {
  const ms = Date.parse(iso);
  if (Number.isNaN(ms)) return [0, 0];

  const seconds = Math.floor(ms / 1000);
  // Date.parse only retains millisecond precision. Recover the full
  // sub-second precision from the ISO fractional-seconds field directly.
  let nanos = 0;
  const match = /\.(\d+)/.exec(iso);
  if (match) {
    // Pad to 9 digits (nanosecond precision); truncate any longer fragment.
    const fracNanos = match[1].slice(0, 9).padEnd(9, "0");
    nanos = parseInt(fracNanos, 10);
  } else {
    // No fractional part: derive nanos from `ms` alone.
    nanos = (ms % 1000) * 1_000_000;
  }
  return [seconds, nanos];
}

// ─── Span name & kind ────────────────────────────────────────────────────────

/**
 * Derives a human-readable span name from an SDK span object.
 *
 * - For span types with a `name` field (agent/function/guardrail/custom/mcp)
 *   the name is used directly.
 * - For handoff spans we render `handoff to <to_agent>` to make the trace
 *   timeline readable.
 * - Otherwise we fall back to the span data's `type` discriminator.
 */
function getSpanName(span: Span<SpanData>): string {
  const data = span.spanData;
  if ("name" in data && isString(data.name)) {
    return data.name;
  }
  if (data.type === "handoff" && isString(data.to_agent)) {
    return `handoff to ${data.to_agent}`;
  }
  return data.type;
}

/**
 * Maps a SpanData type to the corresponding OpenInference span kind.
 *
 * @see https://github.com/Arize-ai/openinference/blob/main/spec/semantic_conventions.md
 */
function getSpanKind(data: SpanData): OpenInferenceSpanKind {
  switch (data.type) {
    case "agent":
      return OpenInferenceSpanKind.AGENT;
    case "generation":
    case "response":
      return OpenInferenceSpanKind.LLM;
    case "function":
    case "handoff":
    case "mcp_tools":
      return OpenInferenceSpanKind.TOOL;
    case "guardrail":
      return OpenInferenceSpanKind.GUARDRAIL;
    default:
      return OpenInferenceSpanKind.CHAIN;
  }
}

// ─── Message extraction ──────────────────────────────────────────────────────

/**
 * Extracts indexed message attributes from a list of chat-style messages.
 *
 * Each message contributes `${prefix}.${i}.message.role`, `.message.content`
 * (or per-content-part attributes for multipart messages), and any
 * `tool_calls` entries.
 */
function extractMessageList(messages: ReadonlyArray<unknown>, prefix: string): Attributes {
  const attrs: Attributes = {};
  let toolCallIdx = 0;

  for (let i = 0; i < messages.length; i++) {
    const msg = messages[i];
    if (!isRecord(msg)) continue;
    const msgPrefix = `${prefix}.${i}`;

    if (isString(msg.role)) {
      attrs[`${msgPrefix}.${MESSAGE_ROLE}`] = msg.role;
    }

    const content = msg.content;
    if (isString(content)) {
      attrs[`${msgPrefix}.${MESSAGE_CONTENT}`] = content;
    } else if (Array.isArray(content)) {
      for (let j = 0; j < content.length; j++) {
        const part = content[j];
        if (!isRecord(part)) continue;
        const partPrefix = `${msgPrefix}.${MESSAGE_CONTENTS}.${j}`;
        if (part.type === "text" && isString(part.text)) {
          attrs[`${partPrefix}.${MESSAGE_CONTENT_TYPE}`] = "text";
          attrs[`${partPrefix}.${MESSAGE_CONTENT_TEXT}`] = part.text;
        }
      }
    }

    if (isString(msg.tool_call_id)) {
      attrs[`${msgPrefix}.${MESSAGE_TOOL_CALL_ID}`] = msg.tool_call_id;
    }

    if (Array.isArray(msg.tool_calls)) {
      for (const tc of msg.tool_calls) {
        if (!isRecord(tc)) continue;
        const tcPrefix = `${msgPrefix}.${MESSAGE_TOOL_CALLS}.${toolCallIdx}`;
        if (isString(tc.id)) {
          attrs[`${tcPrefix}.${TOOL_CALL_ID}`] = tc.id;
        }
        if (isRecord(tc.function)) {
          if (isString(tc.function.name)) {
            attrs[`${tcPrefix}.${TOOL_CALL_FUNCTION_NAME}`] = tc.function.name;
          }
          if (isString(tc.function.arguments) && tc.function.arguments !== "{}") {
            attrs[`${tcPrefix}.${TOOL_CALL_FUNCTION_ARGUMENTS_JSON}`] = tc.function.arguments;
          }
        }
        toolCallIdx++;
      }
    }
  }

  return attrs;
}

// ─── Generation span ─────────────────────────────────────────────────────────

/**
 * Extracts attributes from {@link GenerationSpanData}.
 *
 * In the chat_completions transport, the SDK stores raw ChatCompletion
 * response objects in `data.output[]`, and `data.usage` is `undefined`.
 * In the responses transport, `data.usage` is populated and `data.output`
 * contains plain message dicts.
 *
 * We probe the first element of `data.output` for a `choices` field to decide
 * which extraction path to take.
 */
function getGenerationAttributes(data: GenerationSpanData): Attributes {
  const attrs: Attributes = {};

  if (isString(data.model)) {
    attrs[LLM_MODEL_NAME] = data.model;
  }

  if (isRecord(data.model_config)) {
    const filtered: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(data.model_config)) {
      if (v != null) filtered[k] = v;
    }
    if (Object.keys(filtered).length > 0) {
      attrs[LLM_INVOCATION_PARAMETERS] = safelyJSONStringify(filtered) ?? "";
    }
  }

  if (Array.isArray(data.input) && data.input.length > 0) {
    const inputJson = safelyJSONStringify(data.input);
    if (inputJson) {
      attrs[INPUT_VALUE] = inputJson;
      attrs[INPUT_MIME_TYPE] = MimeType.JSON;
    }
    Object.assign(attrs, extractMessageList(data.input, LLM_INPUT_MESSAGES));
  }

  if (Array.isArray(data.output) && data.output.length > 0) {
    const outputJson = safelyJSONStringify(data.output);
    if (outputJson) {
      attrs[OUTPUT_VALUE] = outputJson;
      attrs[OUTPUT_MIME_TYPE] = MimeType.JSON;
    }

    const first = data.output[0];
    if (isRecord(first) && first.choices !== undefined) {
      // chat_completions transport: output[] are ChatCompletion responses.
      Object.assign(attrs, extractFromChatCompletionResponses(data.output));
    } else {
      // Responses API or generic message-list shape.
      Object.assign(attrs, extractMessageList(data.output, LLM_OUTPUT_MESSAGES));
    }
  }

  if (data.usage) {
    Object.assign(attrs, getGenerationUsageAttributes(data.usage));
  }

  return attrs;
}

/**
 * Extracts output messages and aggregated token counts from an array of
 * ChatCompletion response objects (chat_completions transport).
 *
 * Multiple response objects may be present when the SDK retries or batches
 * model calls. Token counts are summed across all responses.
 */
function extractFromChatCompletionResponses(responses: ReadonlyArray<unknown>): Attributes {
  const attrs: Attributes = {};
  let msgIdx = 0;
  let tcIdx = 0;
  let totalPrompt = 0;
  let totalCompletion = 0;
  let totalCacheRead = 0;
  let totalReasoning = 0;
  let hasUsage = false;

  for (const resp of responses) {
    if (!isRecord(resp)) continue;

    // Token usage
    if (isRecord(resp.usage)) {
      hasUsage = true;
      const usage = resp.usage;
      if (isNumber(usage.prompt_tokens)) totalPrompt += usage.prompt_tokens;
      if (isNumber(usage.completion_tokens)) totalCompletion += usage.completion_tokens;
      // OpenAI / DeepSeek prompt_tokens_details.cached_tokens
      if (
        isRecord(usage.prompt_tokens_details) &&
        isNumber(usage.prompt_tokens_details.cached_tokens)
      ) {
        totalCacheRead += usage.prompt_tokens_details.cached_tokens;
      }
      // o-series completion_tokens_details.reasoning_tokens
      if (
        isRecord(usage.completion_tokens_details) &&
        isNumber(usage.completion_tokens_details.reasoning_tokens)
      ) {
        totalReasoning += usage.completion_tokens_details.reasoning_tokens;
      }
    }

    // Output messages
    if (!Array.isArray(resp.choices)) continue;
    for (const choice of resp.choices) {
      if (!isRecord(choice) || !isRecord(choice.message)) continue;
      const message = choice.message;
      const msgPrefix = `${LLM_OUTPUT_MESSAGES}.${msgIdx}`;

      if (isString(message.role)) {
        attrs[`${msgPrefix}.${MESSAGE_ROLE}`] = message.role;
      }

      const content = message.content;
      if (isString(content)) {
        attrs[`${msgPrefix}.${MESSAGE_CONTENT}`] = content;
      } else if (Array.isArray(content)) {
        for (let j = 0; j < content.length; j++) {
          const part = content[j];
          if (!isRecord(part)) continue;
          const partPrefix = `${msgPrefix}.${MESSAGE_CONTENTS}.${j}`;
          if (part.type === "text" && isString(part.text)) {
            attrs[`${partPrefix}.${MESSAGE_CONTENT_TYPE}`] = "text";
            attrs[`${partPrefix}.${MESSAGE_CONTENT_TEXT}`] = part.text;
          }
        }
      }

      if (Array.isArray(message.tool_calls)) {
        for (const tc of message.tool_calls) {
          if (!isRecord(tc)) continue;
          const tcPrefix = `${msgPrefix}.${MESSAGE_TOOL_CALLS}.${tcIdx}`;
          if (isString(tc.id)) {
            attrs[`${tcPrefix}.${TOOL_CALL_ID}`] = tc.id;
          }
          if (isRecord(tc.function)) {
            if (isString(tc.function.name)) {
              attrs[`${tcPrefix}.${TOOL_CALL_FUNCTION_NAME}`] = tc.function.name;
            }
            if (isString(tc.function.arguments) && tc.function.arguments !== "{}") {
              attrs[`${tcPrefix}.${TOOL_CALL_FUNCTION_ARGUMENTS_JSON}`] = tc.function.arguments;
            }
          }
          tcIdx++;
        }
      }

      msgIdx++;
    }
  }

  if (hasUsage) {
    if (totalPrompt > 0) attrs[LLM_TOKEN_COUNT_PROMPT] = totalPrompt;
    if (totalCompletion > 0) attrs[LLM_TOKEN_COUNT_COMPLETION] = totalCompletion;
    if (totalPrompt + totalCompletion > 0) {
      attrs[LLM_TOKEN_COUNT_TOTAL] = totalPrompt + totalCompletion;
    }
    if (totalCacheRead > 0) {
      attrs[LLM_TOKEN_COUNT_PROMPT_DETAILS_CACHE_READ] = totalCacheRead;
    }
    if (totalReasoning > 0) {
      attrs[LLM_TOKEN_COUNT_COMPLETION_DETAILS_REASONING] = totalReasoning;
    }
  }

  return attrs;
}

/**
 * Extracts token usage attributes from {@link GenerationUsageData}.
 *
 * The SDK uses `input_tokens` / `output_tokens` for generation usage and
 * nests details under a `details` object.
 */
function getGenerationUsageAttributes(usage: GenerationUsageData): Attributes {
  const attrs: Attributes = {};
  if (isNumber(usage.input_tokens)) {
    attrs[LLM_TOKEN_COUNT_PROMPT] = usage.input_tokens;
  }
  if (isNumber(usage.output_tokens)) {
    attrs[LLM_TOKEN_COUNT_COMPLETION] = usage.output_tokens;
  }
  if (isNumber(usage.input_tokens) && isNumber(usage.output_tokens)) {
    attrs[LLM_TOKEN_COUNT_TOTAL] = usage.input_tokens + usage.output_tokens;
  }
  if (isRecord(usage.details)) {
    if (isNumber(usage.details.cached_tokens)) {
      attrs[LLM_TOKEN_COUNT_PROMPT_DETAILS_CACHE_READ] = usage.details.cached_tokens;
    }
    if (isNumber(usage.details.reasoning_tokens)) {
      attrs[LLM_TOKEN_COUNT_COMPLETION_DETAILS_REASONING] = usage.details.reasoning_tokens;
    }
  }
  return attrs;
}

// ─── Function span ───────────────────────────────────────────────────────────

/**
 * Extracts attributes from {@link FunctionSpanData} (tool / function calls).
 */
function getFunctionAttributes(data: FunctionSpanData): Attributes {
  const attrs: Attributes = {};
  attrs[TOOL_NAME] = data.name;
  if (data.input) {
    attrs[INPUT_VALUE] = data.input;
    attrs[INPUT_MIME_TYPE] = MimeType.JSON;
  }
  if (data.output != null) {
    if (isString(data.output)) {
      attrs[OUTPUT_VALUE] = data.output;
      // Heuristic: if the output looks like a JSON object, mark it as JSON.
      if (data.output.length > 1 && data.output.startsWith("{") && data.output.endsWith("}")) {
        attrs[OUTPUT_MIME_TYPE] = MimeType.JSON;
      }
    } else {
      attrs[OUTPUT_VALUE] = safelyJSONStringify(data.output) ?? String(data.output);
    }
  }
  return attrs;
}

// ─── Response span (Responses API) ───────────────────────────────────────────

/**
 * Extracts output messages and tool calls from a Responses API output array.
 */
function extractResponseOutput(output: ReadonlyArray<unknown>): Attributes {
  const attrs: Attributes = {};
  let msgIdx = 0;
  let tcIdx = 0;

  for (const item of output) {
    if (!isRecord(item)) continue;

    if (item.type === "message") {
      const msgPrefix = `${LLM_OUTPUT_MESSAGES}.${msgIdx}`;
      if (isString(item.role)) {
        attrs[`${msgPrefix}.${MESSAGE_ROLE}`] = item.role;
      }
      if (Array.isArray(item.content)) {
        for (let j = 0; j < item.content.length; j++) {
          const part = item.content[j];
          if (!isRecord(part)) continue;
          const partPrefix = `${msgPrefix}.${MESSAGE_CONTENTS}.${j}`;
          if ((part.type === "output_text" || part.type === "text") && isString(part.text)) {
            attrs[`${partPrefix}.${MESSAGE_CONTENT_TYPE}`] = "text";
            attrs[`${partPrefix}.${MESSAGE_CONTENT_TEXT}`] = part.text;
          } else if (part.type === "refusal" && isString(part.refusal)) {
            attrs[`${partPrefix}.${MESSAGE_CONTENT_TYPE}`] = "text";
            attrs[`${partPrefix}.${MESSAGE_CONTENT_TEXT}`] = part.refusal;
          }
        }
      }
      msgIdx++;
    } else if (item.type === "function_call") {
      const msgPrefix = `${LLM_OUTPUT_MESSAGES}.${msgIdx}`;
      attrs[`${msgPrefix}.${MESSAGE_ROLE}`] = "assistant";
      const tcPrefix = `${msgPrefix}.${MESSAGE_TOOL_CALLS}.${tcIdx}`;
      if (isString(item.call_id)) {
        attrs[`${tcPrefix}.${TOOL_CALL_ID}`] = item.call_id;
      }
      if (isString(item.name)) {
        attrs[`${tcPrefix}.${TOOL_CALL_FUNCTION_NAME}`] = item.name;
      }
      if (isString(item.arguments) && item.arguments !== "{}") {
        attrs[`${tcPrefix}.${TOOL_CALL_FUNCTION_ARGUMENTS_JSON}`] = item.arguments;
      }
      tcIdx++;
    }
    // Other item types (file_search_call, web_search_call, computer_call, ...)
    // are not yet supported, matching the Python instrumentation's TODOs.
  }

  return attrs;
}

/**
 * Extracts attributes from {@link ResponseSpanData}.
 *
 * The SDK exposes the input as `_input` (string or list of input items) and
 * the raw `Response` object as `_response` (a plain dict at runtime). We pull
 * out tools, usage, output, instructions and model name from the response.
 */
function getResponseAttributes(data: ResponseSpanData): Attributes {
  const attrs: Attributes = {};

  // Input
  if (data._input != null) {
    if (isString(data._input)) {
      attrs[INPUT_VALUE] = data._input;
    } else if (Array.isArray(data._input)) {
      const json = safelyJSONStringify(data._input);
      if (json) {
        attrs[INPUT_VALUE] = json;
        attrs[INPUT_MIME_TYPE] = MimeType.JSON;
      }
    }
  }

  // Response
  if (!isRecord(data._response)) return attrs;
  const resp = data._response;

  const respJson = safelyJSONStringify(resp);
  if (respJson) {
    attrs[OUTPUT_VALUE] = respJson;
    attrs[OUTPUT_MIME_TYPE] = MimeType.JSON;
  }

  if (isString(resp.model)) {
    attrs[LLM_MODEL_NAME] = resp.model;
  }

  // Token usage. The Responses API uses input_tokens/output_tokens/total_tokens
  // and nests cache/reasoning details under *_tokens_details.
  if (isRecord(resp.usage)) {
    const usage = resp.usage;
    if (isNumber(usage.input_tokens)) attrs[LLM_TOKEN_COUNT_PROMPT] = usage.input_tokens;
    if (isNumber(usage.output_tokens)) attrs[LLM_TOKEN_COUNT_COMPLETION] = usage.output_tokens;
    if (isNumber(usage.total_tokens)) attrs[LLM_TOKEN_COUNT_TOTAL] = usage.total_tokens;
    if (
      isRecord(usage.input_tokens_details) &&
      isNumber(usage.input_tokens_details.cached_tokens)
    ) {
      attrs[LLM_TOKEN_COUNT_PROMPT_DETAILS_CACHE_READ] = usage.input_tokens_details.cached_tokens;
    }
    if (
      isRecord(usage.output_tokens_details) &&
      isNumber(usage.output_tokens_details.reasoning_tokens)
    ) {
      attrs[LLM_TOKEN_COUNT_COMPLETION_DETAILS_REASONING] =
        usage.output_tokens_details.reasoning_tokens;
    }
  }

  // Tools
  if (Array.isArray(resp.tools)) {
    for (let i = 0; i < resp.tools.length; i++) {
      const tool = resp.tools[i];
      if (!isRecord(tool) || tool.type !== "function") continue;
      const schema = safelyJSONStringify({
        type: "function",
        function: {
          name: tool.name,
          description: tool.description,
          parameters: tool.parameters,
          strict: tool.strict,
        },
      });
      if (schema) {
        attrs[`${LLM_TOOLS}.${i}.${TOOL_JSON_SCHEMA}`] = schema;
      }
    }
  }

  // Output messages and function calls
  if (Array.isArray(resp.output)) {
    Object.assign(attrs, extractResponseOutput(resp.output));
  }

  // System instructions become the first input message (matching the Python
  // instrumentation, which prepends a system message at index 0).
  if (isString(resp.instructions) && resp.instructions.length > 0) {
    attrs[`${LLM_INPUT_MESSAGES}.0.${MESSAGE_ROLE}`] = "system";
    attrs[`${LLM_INPUT_MESSAGES}.0.${MESSAGE_CONTENT}`] = resp.instructions;
  }

  return attrs;
}

// ─── MCP list tools span ─────────────────────────────────────────────────────

/**
 * Extracts attributes from {@link MCPListToolsSpanData}.
 */
function getMCPListToolsAttributes(data: MCPListToolsSpanData): Attributes {
  const attrs: Attributes = {};
  if (data.result != null) {
    attrs[OUTPUT_VALUE] = safelyJSONStringify(data.result) ?? "";
    attrs[OUTPUT_MIME_TYPE] = MimeType.JSON;
  }
  return attrs;
}

// ─── Custom span ─────────────────────────────────────────────────────────────

/**
 * Extracts attributes from {@link CustomSpanData}, serialising the user-defined
 * data dict as JSON output.
 */
function getCustomAttributes(data: CustomSpanData): Attributes {
  const attrs: Attributes = {};
  if (isRecord(data.data) && Object.keys(data.data).length > 0) {
    const json = safelyJSONStringify(data.data);
    if (json) {
      attrs[OUTPUT_VALUE] = json;
      attrs[OUTPUT_MIME_TYPE] = MimeType.JSON;
    }
  }
  return attrs;
}

// ─── Status ──────────────────────────────────────────────────────────────────

function setSpanStatus(otelSpan: OtelSpan, span: Span<SpanData>): void {
  if (span.error) {
    let description = span.error.message || "Unknown error";
    if (span.error.data) {
      const dataStr = isString(span.error.data)
        ? span.error.data
        : (safelyJSONStringify(span.error.data) ?? "");
      if (dataStr) {
        description = `${description}: ${dataStr}`;
      }
    }
    otelSpan.setStatus({ code: SpanStatusCode.ERROR, message: description });
  } else {
    otelSpan.setStatus({ code: SpanStatusCode.OK });
  }
}

// ─── Processor ───────────────────────────────────────────────────────────────

/**
 * A {@link TracingProcessor} that bridges `@openai/agents` tracing events to
 * OpenTelemetry spans following the OpenInference semantic conventions.
 *
 * Register it with the agents SDK via
 * {@link OpenAIAgentsInstrumentation.instrument} (preferred) or directly with
 * `setTraceProcessors` / `addTraceProcessor`.
 *
 * @see https://github.com/Arize-ai/openinference/blob/main/spec/semantic_conventions.md
 */
export class OpenInferenceTracingProcessor implements TracingProcessor {
  private readonly oiTracer: OITracer;

  /** trace_id → root OTel span */
  private readonly rootSpans = new Map<string, OtelSpan>();
  /** span_id → OTel span */
  private readonly otelSpans = new Map<string, OtelSpan>();
  /**
   * Tracks in-flight handoffs so that when the destination agent's span starts
   * we can record `graph.node.parent_id` to visualise multi-agent flows.
   *
   * Key: `${to_agent}:${trace_id}`. Value: `from_agent` name.
   *
   * `Map` preserves insertion order, so we use it as an LRU bound by
   * {@link MAX_HANDOFFS_IN_FLIGHT} to guard against unbounded growth when
   * handoff spans never get a follow-up agent span.
   */
  private readonly reverseHandoffs = new Map<string, string>();

  constructor({
    tracerProvider,
    traceConfig,
  }: {
    tracerProvider?: TracerProvider;
    traceConfig?: TraceConfigOptions;
  } = {}) {
    const baseTracer = (tracerProvider ?? trace).getTracer(INSTRUMENTATION_NAME, VERSION);
    this.oiTracer = new OITracer({ tracer: baseTracer, traceConfig });
  }

  async onTraceStart(agentTrace: Trace): Promise<void> {
    const rootSpan = this.oiTracer.startSpan(agentTrace.name, {
      attributes: {
        [OPENINFERENCE_SPAN_KIND]: OpenInferenceSpanKind.AGENT,
        [LLM_SYSTEM]: LLMSystem.OPENAI,
      },
    });
    this.rootSpans.set(agentTrace.traceId, rootSpan);
  }

  async onTraceEnd(agentTrace: Trace): Promise<void> {
    const rootSpan = this.rootSpans.get(agentTrace.traceId);
    if (!rootSpan) return;
    rootSpan.setStatus({ code: SpanStatusCode.OK });
    rootSpan.end();
    this.rootSpans.delete(agentTrace.traceId);
  }

  async onSpanStart(span: Span<SpanData>): Promise<void> {
    if (!span.startedAt) return;

    const parentSpan = span.parentId
      ? this.otelSpans.get(span.parentId)
      : this.rootSpans.get(span.traceId);

    const parentContext = parentSpan
      ? trace.setSpan(context.active(), parentSpan)
      : context.active();

    const otelSpan = this.oiTracer.startSpan(
      getSpanName(span),
      {
        startTime: isoToHrTime(span.startedAt),
        attributes: {
          [OPENINFERENCE_SPAN_KIND]: getSpanKind(span.spanData),
          [LLM_SYSTEM]: LLMSystem.OPENAI,
        },
      },
      parentContext,
    );

    this.otelSpans.set(span.spanId, otelSpan);
  }

  async onSpanEnd(span: Span<SpanData>): Promise<void> {
    const otelSpan = this.otelSpans.get(span.spanId);
    if (!otelSpan) return;
    this.otelSpans.delete(span.spanId);

    // Some span types (e.g. handoff) don't have their final name resolved
    // until the span ends, so refresh it here.
    otelSpan.updateName(getSpanName(span));

    let attrs: Attributes = {};
    const data = span.spanData;
    switch (data.type) {
      case "generation":
        attrs = getGenerationAttributes(data);
        break;
      case "function":
        attrs = getFunctionAttributes(data);
        break;
      case "response":
        attrs = getResponseAttributes(data);
        break;
      case "mcp_tools":
        attrs = getMCPListToolsAttributes(data);
        break;
      case "custom":
        attrs = getCustomAttributes(data);
        break;
      case "handoff":
        this.recordHandoff(data, span.traceId);
        break;
      case "agent":
        this.applyAgentGraphAttributes(otelSpan, data, span.traceId);
        break;
      case "guardrail":
        otelSpan.setAttribute(TOOL_NAME, data.name);
        otelSpan.setAttribute("guardrail.triggered", data.triggered);
        break;
      case "speech":
      case "speech_group":
      case "transcription":
        // These span types carry no additional attributes in the current
        // OpenInference spec. Listed explicitly for exhaustiveness.
        break;
    }

    otelSpan.setAttributes(attrs);
    setSpanStatus(otelSpan, span);

    const endTime = span.endedAt ? isoToHrTime(span.endedAt) : undefined;
    otelSpan.end(endTime);
  }

  async shutdown(_timeout?: number): Promise<void> {
    // The OTel TracerProvider owns flushing/shutdown — nothing to do here.
  }

  async forceFlush(): Promise<void> {
    // The OTel TracerProvider owns flushing — nothing to do here.
  }

  // ─── Private helpers ───────────────────────────────────────────────────────

  /**
   * Records a handoff so that the destination agent's span can later be
   * linked to the source agent via `graph.node.parent_id`.
   */
  private recordHandoff(data: HandoffSpanData, traceId: string): void {
    if (!data.to_agent || !data.from_agent) return;
    const key = `${data.to_agent}:${traceId}`;
    // Re-insert to refresh LRU position
    this.reverseHandoffs.delete(key);
    this.reverseHandoffs.set(key, data.from_agent);
    while (this.reverseHandoffs.size > MAX_HANDOFFS_IN_FLIGHT) {
      const oldest = this.reverseHandoffs.keys().next().value;
      if (oldest === undefined) break;
      this.reverseHandoffs.delete(oldest);
    }
  }

  /**
   * Annotates an agent span with graph-node identifiers, including a parent
   * pointer if this agent was reached via a handoff.
   */
  private applyAgentGraphAttributes(
    otelSpan: OtelSpan,
    data: AgentSpanData,
    traceId: string,
  ): void {
    otelSpan.setAttribute(GRAPH_NODE_ID, data.name);
    const key = `${data.name}:${traceId}`;
    const parentNode = this.reverseHandoffs.get(key);
    if (parentNode) {
      otelSpan.setAttribute(GRAPH_NODE_PARENT_ID, parentNode);
      this.reverseHandoffs.delete(key);
    }
  }
}
