line-length = 100
exclude = [
    ".git",
    ".tox",
    "dist",
]
target-version = "py38"

[lint]
ignore-init-module-imports = true
select = ["E", "F", "W", "I"]

[lint.isort]
force-single-line = false
